# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O4sVDJjHL1L-ehX6BtUshhALSnfbANox
"""

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
df = pd.read_csv(io.BytesIO(uploaded['test.csv']), encoding='latin1', sep = ";")

df.info()

df.head()

df.isnull().sum()

df = df.dropna()

df.isnull().sum()

